// This file is automatically generated.

$.namespace('armadillo.Version');

armadillo.Version.MAJOR = 0;
armadillo.Version.MINOR = 8;
armadillo.Version.BUILD = 640.13;
armadillo.Version.STAMP = 1344793882;
