// This file is automatically generated.

$.namespace('armadillo.Version');

armadillo.Version.MAJOR = 0;
armadillo.Version.MINOR = 8;
armadillo.Version.BUILD = 643.0;
armadillo.Version.STAMP = 1349547115;
