// This file is automatically generated.

$.namespace('armadillo.Version');

armadillo.Version.MAJOR = 0;
armadillo.Version.MINOR = 8;
armadillo.Version.BUILD = 642.1;
armadillo.Version.STAMP = 1346818356;
